version: '3.9'

volumes:
  kong_data: {}

networks:
  kong-net:
    external: false
  about-page-api-net:
    external: false

#======================
#======================
#======================

services:
  kong:
    image: "kong:2.8.1-alpine"
    volumes:
     - ./kong-declarative-config.yml:/tmp/kong-declarative-config.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled
    restart: on-failure:5
    networks:
      - kong-net
    ports:
      - 8000:8000
      - 8443:8443
      # - 8001:8001
      # - 8444:8444

#======================

  backend-about-page-db:
    container_name: backend-about-page-db
    image: postgres:14-alpine
    restart: on-failure:5
    networks:
      - about-page-api-net
    environment:
      POSTGRES_USER: ${ABOUT_PAGE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ABOUT_PAGE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ABOUT_PAGE_POSTGRES_DB}

  backend-about-page:
    container_name: ${ABOUT_PAGE_API_HOST}
    build:
      context: ./backend-about-page
      args:
        PORT: ${ABOUT_PAGE_API_PORT}
        POSTGRES_USER: ${ABOUT_PAGE_POSTGRES_USER}
        POSTGRES_PASSWORD: ${ABOUT_PAGE_POSTGRES_PASSWORD}
        POSTGRES_HOST: backend-about-page-db
        POSTGRES_PORT: 5432
        POSTGRES_DB: ${ABOUT_PAGE_POSTGRES_DB}
    environment:
      PORT: ${ABOUT_PAGE_API_PORT}
      POSTGRES_USER: ${ABOUT_PAGE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ABOUT_PAGE_POSTGRES_PASSWORD}
      POSTGRES_HOST: backend-about-page-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${ABOUT_PAGE_POSTGRES_DB}
    depends_on:
      - backend-about-page-db
    restart: on-failure:5
    networks:
      - kong-net
      - about-page-api-net
    links:
      - backend-about-page-db:backend-about-page-db

#======================

  frontend:
    container_name: ikatoo-frontend
    image: nginx:alpine
    working_dir: /usr/share/nginx/html
    volumes:
      - ./frontend-dist:/usr/share/nginx/html:ro
    ports:
      - ${PORT}:80

